Shader "Custom/SDFVolumeRaymarcher"
{
    Properties
    {
        _NeonColor ("Neon Color", Color) = (1, 0.5, 0, 1)
        _GlowIntensity ("Glow Intensity", Range(0, 5)) = 2.5
    }

    SubShader
    {
        // 1. Move queue into Transparent so empty areas pass through perfectly
        Tags { "RenderType"="Transparent" "RenderPipeline"="UniversalPipeline" "Queue"="Transparent" }
        LOD 100

        Pass
        {
            Name "ForwardLit"
            Tags { "LightMode"="UniversalForward" }

            Blend SrcAlpha OneMinusSrcAlpha
            Cull Front
            ZWrite Off
            ZTest Always

            HLSLPROGRAM
            #pragma vertex vert
            #pragma fragment frag

            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/DeclareDepthTexture.hlsl"

            struct Attributes
            {
                float4 positionOS   : POSITION;
            };

            struct Varyings
            {
                float4 positionCS   : SV_POSITION;
                float3 positionWS   : TEXCOORD0;
                float4 screenPos    : TEXCOORD1;
            };

            float4 _NeonColor;
            float _GlowIntensity;

            #define MAX_STANDALONE_PRIMITIVES 64
            #define MAX_CSG_INSTANCES 32
            #define MAX_TOTAL_CSG_NODES 128

            // --- GLOBAL VECTOR BUFFERS ---
            uniform float4x4 _GlobalCubeMatrices[MAX_STANDALONE_PRIMITIVES];
            uniform float4 _GlobalCubeData[MAX_STANDALONE_PRIMITIVES]; // x = isSubtractive (0 or 1)
            uniform int _GlobalCubeCount;

            uniform float4 _GlobalSpherePositions[MAX_STANDALONE_PRIMITIVES];
            uniform float4 _GlobalSphereRadii[MAX_STANDALONE_PRIMITIVES];   // x = Radius, y = isSubtractive
            uniform int _GlobalSphereCount;

            uniform float4x4 _GlobalCapsuleMatrices[MAX_STANDALONE_PRIMITIVES];
            uniform float4 _GlobalCapsuleData[MAX_STANDALONE_PRIMITIVES]; // x = radius, y = height, z = direction, w = isSubtractive
            uniform int _GlobalCapsuleCount;

            // Universal data slots containing up to 16 distinct sub-limbs
            uniform float4x4 _CharMatrices[MAX_TOTAL_CSG_NODES];
            uniform float4 _CharData[MAX_TOTAL_CSG_NODES];
            uniform int _ActiveCsgInstanceCount;
            uniform float _CsgInstanceOffsets[MAX_CSG_INSTANCES];
            uniform float _CsgAssetTypes[MAX_CSG_INSTANCES];

            Varyings vert(Attributes input)
            {
                Varyings output;
                VertexPositionInputs vertexInput = GetVertexPositionInputs(input.positionOS.xyz);
                output.positionCS = vertexInput.positionCS;
                output.positionWS = vertexInput.positionWS;
                output.screenPos = ComputeScreenPos(vertexInput.positionCS);
                return output;
            }

            #include "SDFPrimitives.hlsl"

            // Pull in the static topology structure generated by the baker script
            #include "Generated/Sword.hlsl"
            #include "Generated/Character.hlsl"
            #include "Generated/SwordCharacter.hlsl"

            float GetSceneSDF(float3 p)
            {
                float finalDist = 10000.0;

                for (int instanceIdx = 0; instanceIdx < _ActiveCsgInstanceCount; instanceIdx++)
                {
                    int baseBufferIndex = (int)_CsgInstanceOffsets[instanceIdx];
                    int assetType = (int)_CsgAssetTypes[instanceIdx];

                    float dInstance = 10000.0;
                    float smoothness = 0.25;

                    if (assetType == 0)
                    {
                        dInstance = GetSwordDist(p, baseBufferIndex, smoothness);
                    }
                    else if (assetType == 1)
                    {
                        dInstance = GetCharacterDist(p, baseBufferIndex, smoothness);
                    }
                    else if (assetType == 2)
                    {
                        dInstance = GetSwordCharacterDist(p, baseBufferIndex, smoothness);
                    }

                    finalDist = smin(finalDist, dInstance, 1.0);
                }

                // --- 1. BASE GEOMETRY PASS (Unions) ---
                for (int i = 0; i < _GlobalCubeCount; i++)
                {
                    if (_GlobalCubeData[i].w < 0.5) {
                        float3 localP = mul(_GlobalCubeMatrices[i], float4(p, 1.0)).xyz;

                        // 🚀 Pass the explicit world half extents from the data vector
                        float dBox = DistanceToBoxLocal(localP, _GlobalCubeData[i].xyz);

                        // Clean uniform distance step, completely glitch-free!
                        finalDist = smin(finalDist, dBox, 1.0);
                    }
                }

                for (int j = 0; j < _GlobalSphereCount; j++)
                {
                    if (_GlobalSphereRadii[j].y < 0.5) {
                        float dSphere = DistanceToSphere(p, _GlobalSpherePositions[j].xyz, _GlobalSphereRadii[j].x);
                        finalDist = smin(finalDist, dSphere, 1.0);
                    }
                }

                for (int k = 0; k < _GlobalCapsuleCount; k++)
                {
                    if (_GlobalCapsuleData[k].w < 0.5) {
                        // localP is now in a clean, unwarped rotated space
                        float3 localP = mul(_GlobalCapsuleMatrices[k], float4(p, 1.0)).xyz;

                        float dCapsule = DistanceToCapsuleLocal(
                            localP,
                            _GlobalCapsuleData[k].x, // World Radius
                            _GlobalCapsuleData[k].y, // World Height
                            (int)_GlobalCapsuleData[k].z // Direction Axis
                        );

                        // No scale correction needed anymore! Space is uniform.
                        finalDist = smin(finalDist, dCapsule, 1.0);
                    }
                }

                // --- 2. CARVING PASS (Subtractions) ---
                for (int i2 = 0; i2 < _GlobalCubeCount; i2++)
                {
                    if (_GlobalCubeData[i2].w > 0.5) {
                        //float3 localP = mul(_GlobalCubeMatrices[i2], float4(p, 1.0)).xyz;
                        //float dBox = DistanceToBoxLocal(localP, _GlobalCubeData[i2].xyz);
                        //finalDist = max(finalDist, -dBox);
                    }
                }

                for (int j2 = 0; j2 < _GlobalSphereCount; j2++)
                {
                    if (_GlobalSphereRadii[j2].y > 0.5) {
                        float dSphere = DistanceToSphere(p, _GlobalSpherePositions[j2].xyz, _GlobalSphereRadii[j2].x);
                        finalDist = max(finalDist, -dSphere);
                    }
                }

                for (int k2 = 0; k2 < _GlobalCapsuleCount; k2++)
                {
                    if (_GlobalCapsuleData[k2].w > 0.5) {
                        float3 localP = mul(_GlobalCapsuleMatrices[k2], float4(p, 1.0)).xyz;

                        float dCapsule = DistanceToCapsuleLocal(
                            localP,
                            _GlobalCapsuleData[k2].x,
                            _GlobalCapsuleData[k2].y,
                            (int)_GlobalCapsuleData[k2].z
                        );

                        finalDist = max(finalDist, -dCapsule);
                    }
                }

                // return finalDist;
                // Right before: return finalDist;

                // Turn the solid union into a hollow neon tube shell!
                float tubeThickness = 0.05; // Adjust this to make the wires thicker or thinner
                finalDist = abs(finalDist) - tubeThickness;

                return finalDist;
            }

            float3 CalculateCSGNormal(float3 p)
            {
                const float k = 0.001; // small epsilon

                // Symmetric tetrahedral direction vectors
                float2 e = float2(1.0, -1.0);

                float d1 = GetSceneSDF(p + e.xyy * k); // (+, -, -)
                float d2 = GetSceneSDF(p + e.yyx * k); // (-, -, +)
                float d3 = GetSceneSDF(p + e.yxy * k); // (-, +, -)
                float d4 = GetSceneSDF(p + e.xxx * k); // (+, +, +)

                float3 normal = e.xyy * d1 +
                                e.yyx * d2 +
                                e.yxy * d3 +
                                e.xxx * d4;

                return normalize(normal);
            }

            float4 frag(Varyings input) : SV_Target
            {
                float2 uv = input.screenPos.xy / input.screenPos.w;

                float rawDepth = SampleSceneDepth(uv);
                float sceneLinearDepth = LinearEyeDepth(rawDepth, _ZBufferParams);

                float3 rayOriginWS = _WorldSpaceCameraPos;
                float3 rayDirWS = normalize(input.positionWS - rayOriginWS);

                float t = 0.0;
                const int MAX_STEPS = 60;
                const float SURFACE_THRESHOLD = 0.01;
                const float MAX_DISTANCE = 60.0;

                bool hitSurface = false;
                float3 hitPosWS = float3(0.0, 0.0, 0.0);

                // --- GLOW ACCUMULATION TRACKER ---
                float accumulatedGlow = 0.0;
                float glowSharpness = 0.5; // Lower = wider/fainter glow, Higher = tighter glow

                [loop]
                for (int i = 0; i < MAX_STEPS; i++)
                {
                    float3 currentPosWS = rayOriginWS + rayDirWS * t;
                    float distanceToScene = GetSceneSDF(currentPosWS);

                    // Track how close the ray passes to the surface to harvest a glow factor
                    // This accumulates intensity whenever a ray "skims" past an object
                    accumulatedGlow += exp(-distanceToScene * glowSharpness);

                    if (distanceToScene <= SURFACE_THRESHOLD)
                    {
                        hitSurface = true;
                        hitPosWS = currentPosWS;
                        break;
                    }

                    if (t > MAX_DISTANCE) break;
                    t += distanceToScene;
                }

                // --- COLOR RENDERING STAGE ---
                float3 finalColor = float3(0.0, 0.0, 0.0); // True black background void

                if (hitSurface)
                {
                    float3 cameraForward = mul((float3x3)UNITY_MATRIX_I_V, float3(0.0, 0.0, -1.0));
                    float3 vectorToHit = hitPosWS - rayOriginWS;
                    float hitEyeDepth = dot(vectorToHit, cameraForward);

                    if (hitEyeDepth < sceneLinearDepth)
                    {
                        float3 normal = CalculateCSGNormal(hitPosWS);
                        float3 viewDirWS = -rayDirWS;

                        // 1. Core Fresnel Edge Glow
                        float edgeGlow = 1.0 - saturate(dot(normal, viewDirWS));
                        edgeGlow = pow(edgeGlow, 4.0);

                        // 2. Connecting Screen-Space Square Grid
                        float targetSquareSizePixels = 40.0;
                        float lineThicknessPixels = 1.5;
                        float2 pixelCoords = uv * _ScreenParams.xy;
                        pixelCoords.y += _Time.y * 25.0;
                        float2 cellCoords = frac(pixelCoords / targetSquareSizePixels) * targetSquareSizePixels;
                        float2 distToEdge = min(cellCoords, targetSquareSizePixels - cellCoords);
                        float2 gridAxisLines = smoothstep(lineThicknessPixels, 0.0, distToEdge);
                        float wireframeIntensity = max(gridAxisLines.x, gridAxisLines.y);

                        // Solid surface composition
                        float3 wireColor = _NeonColor.rgb * wireframeIntensity * 1.5;
                        float3 glowColor = _NeonColor.rgb * edgeGlow * _GlowIntensity;

                        finalColor = wireColor + glowColor;
                    }
                }
                else
                {
                    // If we missed the character, check if we want to render the background glow aura
                    // Normalize the accumulated value down to a soft, faint range
                    float softAura = saturate(accumulatedGlow * 0.02);
                    softAura = pow(softAura, 2.0); // Gives it a nice smooth falloff profile

                    finalColor = _NeonColor.rgb * softAura * _GlowIntensity * 0.4;
                }

                // If there is no surface and no glow aura, cleanly drop pixel execution
                if (hitSurface == false && length(finalColor) < 0.001)
                {
                    discard;
                }

                return float4(finalColor, 1.0);
            }
            ENDHLSL
        }
    }
}
